spring.application.name=reco
#Conexion con MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/reco_db?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#Conexion a la base de datos remota
spring.datasource.url=jdbc:postgresql://ep-shiny-dust-ahlsq8io-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_qJbmtokpif50&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qJbmtokpif50
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
